### ISSUE TITLE
Unable to build using webpack: Error: Invalid name: "calendar-utils/date-adapters/date-fns"

### ISSUE THREAD

**Issue by brunoferreiradev07** [mattlewis92/calendar-utils#25]
While trying to build my project with webpack, the package `normalize-package-data` throws the following error:

>ERROR in ./node_modules/calendar-utils/date-adapters/date-fns/index.js
Module build failed (from ./node_modules/ify-loader/index.js):
Error: Invalid name: "calendar-utils/date-adapters/date-fns"
    at ensureValidName (C:\develop\web\erp\web\node_modules\normalize-package-data\lib\fixer.js:335:15)
    at Object.fixNameField (C:\develop\web\erp\web\node_modules\normalize-package-data\lib\fixer.js:215:5)
    at C:\develop\web\erp\web\node_modules\normalize-package-data\lib\normalize.js:32:38
    at Array.forEach (<anonymous>)
    at normalize (C:\develop\web\erp\web\node_modules\normalize-package-data\lib\normalize.js:31:15)
    at final (C:\develop\web\erp\web\node_modules\read-package-json\read-json.js:411:5)
    at then (C:\develop\web\erp\web\node_modules\read-package-json\read-json.js:160:5)
    at ReadFileContext.<anonymous> (C:\develop\web\erp\web\node_modules\read-package-json\read-json.js:332:20)
    at ReadFileContext.callback (C:\develop\web\erp\web\node_modules\graceful-fs\graceful-fs.js:90:16)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:244:13)
 @ ./node_modules/angular-calendar/date-adapters/date-fns/index.js 4:17-65
 @ ./public/app/main.ts

The documentation (specifically the [_Rules for name field_](https://github.com/npm/normalize-package-data#rules-for-name-field) section) does state the following:

> If name field is given, the value of the name field must be a string. The string may not: **contain the following characters: _/@\s+%_**

**Comment by mattlewis92** [comment]
Thanks for the bug report, I've just released `0.3.0-beta.6` with the fix, will work on getting that to a stable dist tag asap 😄

**Comment by brunoferreiradev07** [comment]
@mattlewis92 Thank you.
